name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Format code with clang-format
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format -i

      - name: Check for uncommitted changes (code style violations)
        run: |
          git diff --exit-code

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

      - name: Configure project with qmake
        run: |
          qmake FinTrack.pro

      - name: Build project
        run: |
          make

      - name: Run tests
        run: |
          ./tests/tst_homewindow
